# Generated by Django 6.0.6 on 2026-07-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertstate',
            name='is_suppressed',
            field=models.BooleanField(default=False, help_text='Operator override: mute automated alerts for this barangay (e.g. a known false positive). State still tracks the level.'),
        ),
    ]
