# Generated by Django 6.0.6 on 2026-06-17 01:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('province_code', models.CharField(max_length=255, unique=True)),
                ('area_square_km', models.FloatField(blank=True, null=True)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('land_height', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['province_code', 'name'], name='barangays_b_provinc_67c673_idx')],
            },
        ),
    ]
