# Generated by Django 6.0.6 on 2026-06-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='province_code',
            field=models.CharField(max_length=255),
        ),
    ]
