# Generated by Django 6.0.6 on 2026-06-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0002_alter_barangay_province_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangay',
            old_name='land_height',
            new_name='land_height_max',
        ),
        migrations.AddField(
            model_name='barangay',
            name='land_height_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='land_height_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
