# Generated by Django 6.0.6 on 2026-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0003_rename_land_height_barangay_land_height_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangay',
            name='distance_to_river_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='flood_susceptibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barangay',
            name='is_downstream',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
