# Generated by Django 6.0.6 on 2026-07-08 02:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0004_barangay_distance_to_river_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangaySusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], db_index=True, max_length=12)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('geom_simplified', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('area_sqm', models.FloatField()),
                ('source_flood_value', models.FloatField()),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='susceptibility_zones', to='barangays.barangay')),
            ],
            options={
                'indexes': [models.Index(fields=['barangay', 'level'], name='barangays_b_baranga_4fe35a_idx')],
                'constraints': [models.UniqueConstraint(fields=('barangay', 'level'), name='uniq_barangay_susceptibility_level')],
            },
        ),
    ]
