# Generated by Django 6.0.6 on 2026-07-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0005_barangaysusceptibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='distance_to_river_km',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='flood_susceptibility',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='is_downstream',
        ),
    ]
