# Generated by Django 6.0.6 on 2026-08-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0006_remove_barangay_distance_to_river_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('susceptibility_level', models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High')], db_index=True, max_length=12)),
                ('loaded_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='barangays.barangay')),
            ],
            options={
                'ordering': ['barangay__name', 'name'],
                'indexes': [models.Index(fields=['barangay', 'susceptibility_level'], name='barangays_s_baranga_93dc8a_idx')],
                'constraints': [models.UniqueConstraint(fields=('barangay', 'name'), name='uniq_barangay_street_name')],
            },
        ),
    ]
