# Generated by Django 6.0.6 on 2026-09-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0007_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangay',
            name='land_height_max',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='land_height_mean',
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='land_height_min',
        ),
    ]
