# Generated by Django 6.0.6 on 2026-10-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0009_gisimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gisimport',
            name='kind',
            field=models.CharField(choices=[('boundary', 'Barangay boundaries'), ('susceptibility', 'Flood susceptibility'), ('streets', 'High-risk streets')], max_length=16),
        ),
    ]
