# Generated by Django 6.0.6 on 2026-07-01 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0004_barangay_distance_to_river_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When flooding occurred (local time).')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major')], default='moderate', max_length=10)),
                ('water_depth_m', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='e.g. DRRMO report, news, PAGASA.', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flood_events', to='barangays.barangay')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['barangay', '-occurred_at'], name='flood_event_baranga_f64cff_idx')],
            },
        ),
    ]
