# Generated by Django 6.0.6 on 2026-07-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodevent',
            name='ended_at',
            field=models.DateTimeField(blank=True, help_text='When flooding receded / event was closed.', null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='people_affected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='people_evacuated',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodevent',
            name='summary',
            field=models.TextField(blank=True, help_text='Narrative account of the event.'),
        ),
        migrations.CreateModel(
            name='FloodEventTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(help_text='When this step happened.')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('flood_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='flood_events.floodevent')),
            ],
            options={
                'ordering': ['occurred_at'],
                'indexes': [models.Index(fields=['flood_event', 'occurred_at'], name='flood_event_flood_e_4ee307_idx')],
            },
        ),
    ]
