# Generated by Django 6.0.6 on 2026-07-06 09:08

import django.db.models.deletion
import flood_events.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_events', '0004_floodevent_reported_by_floodevent_source_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodEventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(help_text='When the evidence was captured.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flood_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='flood_events.floodevent')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='FloodEventReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=flood_events.models.report_image_path)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flood_events.floodeventreport')),
            ],
        ),
        migrations.AddIndex(
            model_name='floodeventreport',
            index=models.Index(fields=['flood_event', '-occurred_at'], name='flood_event_flood_e_51e02c_idx'),
        ),
    ]
