# Generated by Django 6.0.6 on 2026-10-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_events', '0005_floodeventreport_floodeventreportimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodevent',
            name='peak_rainfall_mm_hr',
            field=models.FloatField(blank=True, help_text='Peak rainfall intensity in mm/hr (operator-entered).', null=True),
        ),
    ]
