# Generated by Django 6.0.6 on 2026-10-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flood_events', '0006_floodevent_peak_rainfall_mm_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='floodevent',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='floodeventchange',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('confirmed', 'Confirmed'), ('resolved', 'Resolved'), ('deleted', 'Deleted'), ('archived', 'Archived'), ('restored', 'Restored')], default='updated', max_length=10),
        ),
    ]
