# Generated by Django 6.0.6 on 2026-10-10 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_barangay(apps, schema_editor):
    """Existing operator reports inherit their event's barangay."""
    Report = apps.get_model("flood_events", "FloodEventReport")
    for report in Report.objects.filter(barangay__isnull=True).select_related("flood_event"):
        report.barangay_id = report.flood_event.barangay_id
        report.save(update_fields=["barangay"])


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0010_gisimport_streets_kind'),
        ('flood_events', '0007_floodevent_archived_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='floodeventreport',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flood_reports', to='barangays.barangay'),
        ),
        migrations.AddField(
            model_name='floodeventreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodeventreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodeventreport',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floodeventreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='floodeventreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flood_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='floodeventreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='verified', max_length=10),
        ),
        migrations.AlterField(
            model_name='floodeventreport',
            name='flood_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='flood_events.floodevent'),
        ),
        migrations.RunPython(backfill_barangay, migrations.RunPython.noop),
    ]
