# Generated by Django 6.0.6 on 2026-07-06 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPoiChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poi_type', models.CharField(choices=[('evacuation', 'Evacuation center'), ('hotspot', 'Flood hotspot')], db_index=True, max_length=12)),
                ('poi_id', models.PositiveIntegerField()),
                ('name', models.CharField(help_text='POI name at the time of the edit.', max_length=255)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('moved', 'Moved'), ('deleted', 'Deleted')], max_length=10)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['poi_type', '-created_at'], name='poi_mappoic_poi_typ_bd351c_idx')],
            },
        ),
    ]
