# Generated by Django 6.0.6 on 2026-07-06 08:52

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0004_barangay_distance_to_river_km_and_more'),
        ('poi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('radius_m', models.PositiveIntegerField(default=300, help_text='Advisory radius in metres.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Why this area floods (e.g. clogged canal).')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flood_hotspots', to='barangays.barangay')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
