# Generated by Django 6.0.6 on 2026-07-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0002_floodhotspot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloodHotspot',
        ),
    ]
