# Generated by Django 6.0.6 on 2026-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poi', '0003_delete_floodhotspot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoichange',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('moved', 'Moved'), ('deleted', 'Deleted'), ('archived', 'Archived'), ('restored', 'Restored')], max_length=10),
        ),
    ]
