# Generated by Django 6.0.6 on 2026-07-23 04:05

import risk_score.models.risk_config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_score', '0004_update_default_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskconfig',
            name='accumulation_curve',
            field=models.JSONField(default=risk_score.models.risk_config.default_accumulation_curve),
        ),
        migrations.AddField(
            model_name='riskconfig',
            name='combination_mode',
            field=models.CharField(choices=[('weighted_sum', 'weighted_sum'), ('rainfall_gated', 'rainfall_gated')], default='rainfall_gated', max_length=20),
        ),
        migrations.AddField(
            model_name='riskconfig',
            name='rainfall_curve',
            field=models.JSONField(default=risk_score.models.risk_config.default_rainfall_curve),
        ),
        migrations.AddField(
            model_name='riskconfig',
            name='zone_aggregation',
            field=models.CharField(choices=[('mean', 'mean'), ('max', 'max'), ('area_weighted', 'area_weighted')], default='mean', max_length=16),
        ),
    ]
