# Generated by Django 6.0.6 on 2026-07-23 05:16

from django.db import migrations, models


def mean_to_area_weighted(apps, schema_editor):
    """Move configs off the old 'mean' default onto area-weighted aggregation.

    'mean' was only ever the initial column default (migration 0005), never a
    deliberate operator choice on this branch, so flip those rows. Leave 'max'
    (a real cautious choice) untouched.
    """
    RiskConfig = apps.get_model("risk_score", "RiskConfig")
    RiskConfig.objects.filter(zone_aggregation="mean").update(zone_aggregation="area_weighted")


def area_weighted_to_mean(apps, schema_editor):
    RiskConfig = apps.get_model("risk_score", "RiskConfig")
    RiskConfig.objects.filter(zone_aggregation="area_weighted").update(zone_aggregation="mean")


class Migration(migrations.Migration):

    dependencies = [
        ('risk_score', '0005_riskconfig_accumulation_curve_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskconfig',
            name='zone_aggregation',
            field=models.CharField(choices=[('mean', 'mean'), ('max', 'max'), ('area_weighted', 'area_weighted')], default='area_weighted', max_length=16),
        ),
        migrations.RunPython(mean_to_area_weighted, area_weighted_to_mean),
    ]
