# Generated by Django 6.0.6 on 2026-06-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rainfall_strength', models.DecimalField(decimal_places=2, max_digits=11)),
                ('forecast_strength', models.DecimalField(decimal_places=2, max_digits=11)),
                ('rate_of_change', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
