# Generated by Django 6.0.6 on 2026-06-18 03:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0002_alter_barangay_province_code'),
        ('rainfall_fetch', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rainfall',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='forecast_strength',
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='rainfall_strength',
        ),
        migrations.AddField(
            model_name='rainfall',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_readings', to='barangays.barangay'),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='current_rainfall_strength',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_1hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_2hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_3hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_4hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='recorded_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2026, 6, 18, 3, 43, 28, 341830, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='rainfall',
            index=models.Index(fields=['barangay', '-recorded_at'], name='rainfall_fe_baranga_bd46a9_idx'),
        ),
    ]
