# Generated by Django 6.0.6 on 2026-07-01 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall_fetch', '0002_alter_rainfall_options_remove_rainfall_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfall',
            name='accumulated_12hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='accumulated_24hr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='accumulated_6hr',
            field=models.FloatField(default=0),
        ),
    ]
