# Generated by Django 6.0.6 on 2026-09-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall_fetch', '0003_rainfall_accumulated_12hr_rainfall_accumulated_24hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_150min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_210min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_30min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_90min',
            field=models.FloatField(default=0),
        ),
    ]
