# Generated by Django 6.0.6 on 2026-09-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall_fetch', '0004_rainfall_forecast_strength_150min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rainfall',
            name='accumulated_7day',
            field=models.FloatField(default=0),
        ),
    ]
