# Generated by Django 6.0.6 on 2026-09-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall_fetch', '0005_rainfall_accumulated_7day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rainfall',
            name='forecast_strength_1hr',
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='forecast_strength_2hr',
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='forecast_strength_3hr',
        ),
        migrations.RemoveField(
            model_name='rainfall',
            name='forecast_strength_4hr',
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_105min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_120min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_135min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_15min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_165min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_180min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_195min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_225min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_240min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_45min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_60min',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='rainfall',
            name='forecast_strength_75min',
            field=models.FloatField(default=0),
        ),
    ]
