# Generated by Django 6.0.6 on 2026-09-24 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0008_remove_barangay_land_height_max_and_more'),
        ('rainfall_fetch', '0006_remove_rainfall_forecast_strength_1hr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayRainfallGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_lat', models.FloatField()),
                ('grid_lon', models.FloatField()),
                ('discovered_at', models.DateTimeField(auto_now=True)),
                ('barangay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rainfall_grid', to='barangays.barangay')),
            ],
            options={
                'indexes': [models.Index(fields=['grid_lat', 'grid_lon'], name='rainfall_fe_grid_la_42f5c4_idx')],
            },
        ),
    ]
