# Generated by Django 6.0.6 on 2026-10-02 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0008_remove_barangay_land_height_max_and_more'),
        ('rainfall_fetch', '0007_barangayrainfallgrid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRainfall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField()),
                ('precipitation', models.FloatField(default=0)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rainfall', to='barangays.barangay')),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['hour'], name='rainfall_fe_hour_5a2c2b_idx')],
                'constraints': [models.UniqueConstraint(fields=('barangay', 'hour'), name='uniq_hourly_rainfall')],
            },
        ),
    ]
