# Generated by Django 6.0.6 on 2026-10-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rainfall_fetch', '0008_hourly_rainfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainfallSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_model', models.CharField(choices=[('default', 'Open-Meteo default (best match)'), ('ecmwf_ifs025', 'ECMWF IFS 0.25°')], default='default', help_text='Which Open-Meteo weather model supplies rainfall data.', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
