# Generated by Django 6.0.6 on 2026-07-28 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0006_remove_barangay_distance_to_river_km_and_more'),
        ('evacuation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evacuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('stood_down', 'Stood down')], db_index=True, default='active', max_length=12)),
                ('trigger', models.CharField(choices=[('automated', 'Automated'), ('operator', 'Operator')], max_length=12)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('final_roster', models.PositiveIntegerField(blank=True, null=True)),
                ('final_safe', models.PositiveIntegerField(blank=True, null=True)),
                ('final_moving', models.PositiveIntegerField(blank=True, null=True)),
                ('final_unaccounted', models.PositiveIntegerField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evacuations', to='barangays.barangay')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='Operator who pinged; null when automated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='EvacuationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notified', 'Notified'), ('moving', 'Moving'), ('safe', 'Safe'), ('unaccounted', 'Unaccounted')], default='notified', max_length=12)),
                ('resolved_via', models.CharField(blank=True, choices=[('center', 'Reached center'), ('left_zone', 'Left danger zone')], max_length=12)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(blank=True, help_text='Set when resolved_via=center.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='evacuation.evacuationcenter')),
                ('evacuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='evacuation.evacuation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='evacuation',
            index=models.Index(fields=['status', '-opened_at'], name='evacuation__status_a0d49d_idx'),
        ),
        migrations.AddConstraint(
            model_name='evacuation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('barangay',), name='uniq_active_evacuation_per_barangay'),
        ),
        migrations.AddIndex(
            model_name='evacuationstatus',
            index=models.Index(fields=['evacuation', 'status'], name='evacuation__evacuat_3d4b1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='evacuationstatus',
            constraint=models.UniqueConstraint(fields=('evacuation', 'user'), name='uniq_evacuation_user'),
        ),
    ]
