# Generated by Django 6.0.6 on 2026-10-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0003_contacts_and_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evacuationcenterimage',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='evacuationcenterimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
