# Generated by Django 6.0.6 on 2026-10-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0004_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='archived_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
