# Generated by Django 6.0.6 on 2026-10-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0005_evacuationcenter_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuationcenter',
            name='capacity_unit',
            field=models.CharField(blank=True, help_text="What `capacity` counts, e.g. 'beds'.", max_length=30),
        ),
    ]
