# Generated by Django 6.0.6 on 2026-10-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation', '0006_capacity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='evacuation',
            name='zones',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
