# Generated by Django 6.0.6 on 2026-07-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_operationaltoggles_organizationsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionpolicy',
            name='evacuation_status_retention_days',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
