# Generated by Django 6.0.6 on 2026-09-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_retentionpolicy_evacuation_status_retention_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationaltoggles',
            name='broadcast_enabled',
        ),
        migrations.RemoveField(
            model_name='organizationsettings',
            name='alert_footer',
        ),
    ]
