# Generated by Django 6.0.6 on 2026-07-01 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('normal_level', models.FloatField(help_text='Normal operating level in metres (~crest).')),
                ('critical_level', models.FloatField(help_text='Flood-critical level in metres.')),
                ('source_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DamReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_level', models.FloatField(help_text='Metres.')),
                ('turbidity', models.FloatField(blank=True, help_text='NTU (Lubog station).', null=True)),
                ('rate_of_change', models.FloatField(blank=True, help_text='Metres per hour vs the previous reading.', null=True)),
                ('is_spilling', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Reading time reported by the source.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('dam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='dam_level.dam')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['dam', '-recorded_at'], name='dam_level_d_dam_id_c5b360_idx')],
            },
        ),
    ]
