# Generated by Django 6.0.6 on 2026-07-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam_level', '0002_seed_pasonanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='damreading',
            name='source',
            field=models.CharField(choices=[('scraper', 'Scraper'), ('manual', 'Manual (operator)')], default='scraper', help_text='Where this reading came from (scraper, or manual operator entry).', max_length=10),
        ),
    ]
