# Generated by Django 6.0.6 on 2026-07-06 08:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam_level', '0003_damreading_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dam',
            name='influence_radius_km',
            field=models.FloatField(default=8.0, help_text='Distance beyond which the dam no longer contributes flood hazard.'),
        ),
        migrations.AddField(
            model_name='dam',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Dam location (lng/lat).', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='dam',
            name='river',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, help_text='River corridor fed by the dam (e.g. the Tumaga River).', null=True, srid=4326),
        ),
    ]
