# Generated by Django 6.0.6 on 2026-10-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_notification_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
